// <auto-generated />
using System;
using GeodeDiscord.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeodeDiscord.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231024163035_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("GeodeDiscord.Database.Entities.Quote", b =>
                {
                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("authorId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("channelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("extraAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("jumpUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("lastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("quoterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("replyAuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("messageId");

                    b.HasIndex("authorId");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
