// <auto-generated />
using System;
using GeodeDiscord.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeodeDiscord.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204224203_QuoteAllAttachments")]
    partial class QuoteAllAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("GeodeDiscord.Database.Entities.Guess", b =>
                {
                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("guessId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("guessedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("quoteMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("startedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("messageId");

                    b.HasIndex("guessedAt");

                    b.HasIndex("quoteMessageId");

                    b.HasIndex("userId");

                    b.ToTable("guesses");
                });

            modelBuilder.Entity("GeodeDiscord.Database.Entities.Quote", b =>
                {
                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("authorId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("channelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("jumpUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("lastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("quoterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("replyAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("replyContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("replyMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("messageId");

                    b.HasIndex("authorId");

                    b.HasIndex("id")
                        .IsUnique();

                    b.HasIndex("name");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("GeodeDiscord.Database.Entities.StickyRole", b =>
                {
                    b.Property<ulong>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("roleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("userId", "roleId");

                    b.HasIndex("roleId");

                    b.HasIndex("userId");

                    b.ToTable("stickyRoles");
                });

            modelBuilder.Entity("GeodeDiscord.Database.Entities.Guess", b =>
                {
                    b.HasOne("GeodeDiscord.Database.Entities.Quote", "quote")
                        .WithMany()
                        .HasForeignKey("quoteMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("quote");
                });

            modelBuilder.Entity("GeodeDiscord.Database.Entities.Quote", b =>
                {
                    b.OwnsMany("GeodeDiscord.Database.Entities.Quote+Attachment", "attachments", b1 =>
                        {
                            b1.Property<ulong>("id")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("QuotemessageId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("contentType")
                                .HasColumnType("TEXT");

                            b1.Property<string>("description")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("isSpoiler")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("size")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("url")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("id");

                            b1.HasIndex("QuotemessageId");

                            b1.ToTable("Attachment");

                            b1.WithOwner()
                                .HasForeignKey("QuotemessageId");
                        });

                    b.OwnsMany("GeodeDiscord.Database.Entities.Quote+Embed", "embeds", b1 =>
                        {
                            b1.Property<ulong>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("QuotemessageId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("authorIconUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("authorName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("authorUrl")
                                .HasColumnType("TEXT");

                            b1.Property<uint?>("color")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("footerIconUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("footerText")
                                .HasColumnType("TEXT");

                            b1.Property<string>("imageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("providerName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("providerUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("thumbnailUrl")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("timestamp")
                                .HasColumnType("TEXT");

                            b1.Property<string>("title")
                                .HasColumnType("TEXT");

                            b1.Property<string>("type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("url")
                                .HasColumnType("TEXT");

                            b1.Property<string>("videoUrl")
                                .HasColumnType("TEXT");

                            b1.HasKey("id");

                            b1.HasIndex("QuotemessageId");

                            b1.ToTable("Embed");

                            b1.WithOwner()
                                .HasForeignKey("QuotemessageId");

                            b1.OwnsMany("GeodeDiscord.Database.Entities.Quote+Embed+Field", "fields", b2 =>
                                {
                                    b2.Property<ulong>("id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<ulong>("Embedid")
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("inline")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("name")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("value")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("id");

                                    b2.HasIndex("Embedid");

                                    b2.ToTable("Field");

                                    b2.WithOwner()
                                        .HasForeignKey("Embedid");
                                });

                            b1.Navigation("fields");
                        });

                    b.Navigation("attachments");

                    b.Navigation("embeds");
                });
#pragma warning restore 612, 618
        }
    }
}
