// <auto-generated />
using System;
using GeodeDiscord.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeodeDiscord.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("GeodeDiscord.Database.Entities.Quote", b =>
                {
                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("authorIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("authorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("authorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("extraAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("jumpUrl")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("replyAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("messageId", "name");

                    b.ToTable("quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
